const assets = [
  // Backgrounds
  'images/birds.gif',
  'images/backgrounds/bg1.jpg',
  'images/backgrounds/bg2.jpg',
  'images/backgrounds/bg3.jpg',
  'images/backgrounds/bg4.jpg',
  'images/backgrounds/bg5.jpg',
  'images/backgrounds/bg6.jpg',
  'images/backgrounds/bg7.jpg',
  'images/backgrounds/bg8.jpg',
  // Level Backgrounds
  'images/game/level1.jpg',
  'images/game/level2.jpg',
  'images/game/level3.jpg',
  'images/game/level4.jpg',
  // Level 1
  'images/game/green.jpg',
  'images/game/red.jpg',
  'images/game/orange_c.jpg',
  'images/game/yellow.jpg',
  'images/game/kiwi.jpg',
  'images/game/strawberry.jpg',
  'images/game/orange.jpg',
  'images/game/banana.jpg',
  // Level 2
  'images/game/bird.jpg',
  'images/game/dog.jpg',
  'images/game/frog.jpg',
  'images/game/fox.jpg',
  'images/game/den.jpg',
  'images/game/nest.jpg',
  'images/game/pond.jpg',
  'images/game/doghouse.jpg',
  // Level 3
  'images/game/circle.jpg',
  'images/game/rectangle.jpg',
  'images/game/square.jpg',
  'images/game/triangle.jpg',
  'images/game/clock.jpg',
  'images/game/tv.jpg',
  'images/game/tray.jpg',
  'images/game/tree.jpg',
  // Level 4
  'images/game/fireman.jpg',
  'images/game/nurse.jpg',
  'images/game/teacher.jpg',
  'images/game/baker.jpg',
  'images/game/firetruck.jpg',
  'images/game/hospital.jpg',
  'images/game/school.jpg',
  'images/game/bakery.jpg',
  // Cursors
  'cursors/left_ptr.cur',
  'cursors/plus.cur',
  'cursors/pointer.cur',
  // Sounds
  'audio/magicwand.mp3',
  'audio/tictoc.mp3',
  'audio/error.mp3',
  'audio/shutter.mp3',
  'audio/click2.mp3',
  'audio/swoosh.mp3',
  'audio/trombone.mp3',
  'audio/tada.mp3',
  'audio/ding.mp3',
  'audio/click.mp3'
]
